project:
  type: book
  output-dir: docs/
  resources:
    - 'www/geogebra/*.ggb'
    - 'julia-examples/*.ipynb'

book:
  title: Stochastic Control and Decision Theory
  author: 
    - name: Aditya Mahajan
      url: "https://adityam.github.io"
      affiliation: McGill University
      affiliation-url: "https://www.mcgill.ca/ece"
  description: "Course Notes for ECSE 506 (McGill University)"
  site-url: "https://adityam.github.io/stochastic-control/"

  repo-url: "https://github.com/adityam/stochastic-control"
  repo-actions: [edit]
  repo-branch: quarto
  reader-mode: true

    # google-analytics:
    #   tracking-id: "G-GWP0HLS7WV"
    #   storage: none

  navbar:
    background: dark
    title: false
    pinned: false
    search: false
    left:
      # - href: ../index.html
      #   text: Home
    - href: ../stochastic-control/index.html
      text: Stochastic Control
        # - href: ../multi-agent-systems/index.html
        #   text: Multi-Agent Systems

  sidebar:
    # background: light
    collapse-level: 2
    pinned: false
    style : floating

  chapters:
    - index.qmd
    - part: "Stochastic Optimization"
      chapters:
        - stochastic-optimization/intro.qmd
        - stochastic-optimization/newsvendor.qmd
        - stochastic-optimization/certainty-equivalence.qmd
        - stochastic-optimization/interchange.qmd
    - part: "MDPs"
      chapters:
        - mdps/intro.qmd
        - mdps/gambling.qmd
        - mdps/inventory-management.qmd
        - mdps/monotone-mdps.qmd
        - mdps/monotone-examples.qmd
        - mdps/reward-shaping.qmd
        - mdps/optimal-stopping.qmd
        - mdps/inf-horizon.qmd
        - mdps/mdp-algorithms.qmd
        - mdps/inventory-management-revisited.qmd
        - mdps/mobile-edge-computing.qmd
        - mdps/computational-complexity-vi.qmd
        - mdps/martingale.qmd
        - mdps/linear-programming.qmd
        - mdps/lipschitz-mdps.qmd
        - mdps/periodic-mdps.qmd
    - part: "POMDPs"
      chapters:
        - pomdps/intro.qmd
        - pomdps/sequential-hypothesis.qmd
    - part: "Approx DP"
      chapters:
          - approx-mdps/approx-DP.qmd
          - approx-mdps/policy-loss.qmd
          - approx-mdps/model-approximation.qmd
      #   - approx-mdps/regularized-mdps.qmd
    - part: "Risk sensitive MDPs"
      chapters:
          - risk-sensitive/risk-sensitive-utility.qmd
          - risk-sensitive/risk-sensitive-mdps.qmd
    - part: "Linear systems"
      chapters:
          - linear-systems/lqr.qmd
          - linear-systems/large-scale-systems.qmd
    - part: "RL"
      chapters:
        - rl/stochastic-approximation.qmd
    - part: "Dec-POMDPs"
      chapters:
        - dec-pomdps/designers-approach.qmd
    - part: "Probability Appendix"
      chapters:
        - probability/convergence.qmd
        - probability/sub-gaussian.qmd
        - probability/change-of-measure.qmd
        - probability/IPM.qmd
        - probability/markov-chains.qmd
        - probability/martingales.qmd
        - probability/stochastic-stability.qmd

    - part: "Linear Algebra Appendix"
      chapters:
        - linear-algebra/matrix-relationships.qmd
        - linear-algebra/positive-definite-matrix.qmd
        - linear-algebra/trace.qmd
        - linear-algebra/infinite-product-of-matrices.qmd
        - linear-algebra/svd.qmd
        - linear-algebra/rkhs.qmd
    - part: "Convexity Appendix"
      chapters:
        - convexity/convexity.qmd
        - convexity/duality.qmd

    - references.qmd
    - part: "Assignments"
      chapters:
        - assignments/01.qmd
        - assignments/02.qmd

bibliography: references.bib
csl: _extensions/csl/acm-siggraph.csl

format:
  html:
    author:
      - name: Aditya Mahajan
        url: http://www.cim.mcgill.ca/~adityam
        affiliation: McGill University
        affiliation-url: http://www.mcgill.ca/ece
    citation:
      type: webpage
      container-title: "Course notes for Stochastic Control and Decision Theorey"
        # google-scholar: true
    theme: 
      light: 
        - lumen
        - static/css/style.scss
      dark: 
        - darkly
        - static/css/style.scss
    include-in-header: 
      - static/html/mathjax.html
      - static/html/clicky.html

    reference-location: margin
      #    citation-location: margin
    filters:
      - _extensions/schochastics/nutshell/nutshell.lua
    published-title: Updated
    date: last-modified
    notebook-links: inline

    embed-resources: false
    smooth-scroll: true

    jupyter: julia-1.9
    freeze: true
