baseURL       : "https://adityam.github.io/stochastic-control/"

languageCode  : "en-us"
title         : "ECSE 506: Stochastic Control and Decision Theory"
theme         : coursepage

pluralizelisttitles: fasle
preserveTaxonomyNames: true

enableGitInfo: true

metaDataFormat: yaml
publishDir    : docs

params:
  instructor : Aditya Mahajan
  homepage   : "http://www.cim.mcgill.ca/~adityam/"
  term   : "Winter 2018"
  disqus : "ecse506"

