baseURL       : "https://adityam.github.io/stochastic-control/"

languageCode  : "en-us"
title         : "ECSE 506: Stochastic Control and Decision Theory"
theme         : coursepage

pluralizelisttitles: fasle
preserveTaxonomyNames: true

enableGitInfo: true

metaDataFormat: yaml
publishDir    : docs

params:
  instructor : Aditya Mahajan
  homepage   : "http://www.cim.mcgill.ca/~adityam/"
  term   : "Winter 2022"
  disqus : "ecse506"


security:
  enableInlineShortcodes: false
  exec:
    allow:
    - ^dart-sass-embedded$
    - ^go$
    - ^npx$
    - ^postcss$
    - ^pandoc$
    osEnv:
    - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
    - ^HUGO_
  http:
    methods:
    - (?i)GET|POST
    urls:
    - .*


