baseURL       : "http://www.cim.mcgill.ca/~decinfo/courses/ecse506/winter-2018/"

languageCode  : "en-us"
title         : "ECSE 506: Stochastic Control and Decision Theory"
theme         : coursepage

metaDataFormat: yaml
publishDir    : docs

params:
  instructor : Aditya Mahajan
  homepage   : "http://www.cim.mcgill.ca/~adityam/"
  term   : "Winter 2018"
  disqus : "ecse506"
